# Generated by Django 3.2.3 on 2021-06-07 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200, verbose_name='téléphone')),
                ('url', models.URLField()),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(choices=[('Subject', 'Subject'), ('Sales & marketing', 'Sales & marketing'), ('Creative Design', 'Creative Design'), ('UI/UX', 'UI/UX')], max_length=50, verbose_name='sujet')),
                ('message', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='img')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('job', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'employé',
                'verbose_name_plural': 'employés',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('address', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'emplacement',
                'verbose_name_plural': 'emplacements',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200, verbose_name='icône')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('link', models.URLField(verbose_name='lien')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'réseau social',
                'verbose_name_plural': 'réseaux sociaux',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200, verbose_name='icône')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('link', models.URLField(verbose_name='lien')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.employee', verbose_name='employé')),
            ],
            options={
                'verbose_name': "réseau social d'un employé",
                'verbose_name_plural': 'réseaux sociaux des employés',
            },
        ),
    ]
