# Generated by Django 3.2.3 on 2021-06-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'A propos', 'verbose_name_plural': 'A propos'},
        ),
    ]
