# Generated by Django 3.2.3 on 2021-06-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='formats',
            field=models.CharField(max_length=50, null=True, verbose_name='format'),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
