# Generated by Django 3.2.3 on 2021-06-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210608_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='formats',
            field=models.CharField(choices=[('MP4', 'MP4')], max_length=50, null=True, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='formats',
            field=models.CharField(choices=[('JPG', 'JPG'), ('PNG', 'PNG'), ('JPEG', 'JPEG')], max_length=50, null=True, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(null=True, verbose_name='durée'),
        ),
    ]
