# Generated by Django 3.2.3 on 2021-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210608_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0, null=True, verbose_name='vues'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='views',
            field=models.IntegerField(default=0, null=True, verbose_name='vues'),
        ),
    ]
